// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: board.proto

package board

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Board struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CollaboratorIds []int64                `protobuf:"varint,3,rep,packed,name=collaborator_ids,json=collaboratorIds,proto3" json:"collaborator_ids,omitempty"`
	Wallpapers      []string               `protobuf:"bytes,4,rep,name=wallpapers,proto3" json:"wallpapers,omitempty"`
	Lists           []*List                `protobuf:"bytes,5,rep,name=lists,proto3" json:"lists,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Board) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Board) GetCollaboratorIds() []int64 {
	if x != nil {
		return x.CollaboratorIds
	}
	return nil
}

func (x *Board) GetWallpapers() []string {
	if x != nil {
		return x.Wallpapers
	}
	return nil
}

func (x *Board) GetLists() []*List {
	if x != nil {
		return x.Lists
	}
	return nil
}

func (x *Board) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Board) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cards         []*Card                `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *List) Reset() {
	*x = List{}
	mi := &file_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{1}
}

func (x *List) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *List) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *List) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *List) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *List) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AssigneeIds   []int64                `protobuf:"varint,4,rep,packed,name=assignee_ids,json=assigneeIds,proto3" json:"assignee_ids,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{2}
}

func (x *Card) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Card) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Card) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Card) GetAssigneeIds() []int64 {
	if x != nil {
		return x.AssigneeIds
	}
	return nil
}

func (x *Card) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Card) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Wallpapes     []string               `protobuf:"bytes,2,rep,name=wallpapes,proto3" json:"wallpapes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest) Reset() {
	*x = CreateBoardRequest{}
	mi := &file_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest) ProtoMessage() {}

func (x *CreateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBoardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBoardRequest) GetWallpapes() []string {
	if x != nil {
		return x.Wallpapes
	}
	return nil
}

type CreateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardResponse) Reset() {
	*x = CreateBoardResponse{}
	mi := &file_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardResponse) ProtoMessage() {}

func (x *CreateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardResponse.ProtoReflect.Descriptor instead.
func (*CreateBoardResponse) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type CollaborateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BoardId        int64                  `protobuf:"varint,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	CollaboratorId int64                  `protobuf:"varint,2,opt,name=collaborator_id,json=collaboratorId,proto3" json:"collaborator_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollaborateRequest) Reset() {
	*x = CollaborateRequest{}
	mi := &file_board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollaborateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaborateRequest) ProtoMessage() {}

func (x *CollaborateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaborateRequest.ProtoReflect.Descriptor instead.
func (*CollaborateRequest) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{5}
}

func (x *CollaborateRequest) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

func (x *CollaborateRequest) GetCollaboratorId() int64 {
	if x != nil {
		return x.CollaboratorId
	}
	return 0
}

type CollaborateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollaborateResponse) Reset() {
	*x = CollaborateResponse{}
	mi := &file_board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollaborateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaborateResponse) ProtoMessage() {}

func (x *CollaborateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaborateResponse.ProtoReflect.Descriptor instead.
func (*CollaborateResponse) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{6}
}

func (x *CollaborateResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type DeleteCollaboratorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BoardId        int64                  `protobuf:"varint,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	CollaboratorId int64                  `protobuf:"varint,2,opt,name=collaborator_id,json=collaboratorId,proto3" json:"collaborator_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteCollaboratorRequest) Reset() {
	*x = DeleteCollaboratorRequest{}
	mi := &file_board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollaboratorRequest) ProtoMessage() {}

func (x *DeleteCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCollaboratorRequest) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

func (x *DeleteCollaboratorRequest) GetCollaboratorId() int64 {
	if x != nil {
		return x.CollaboratorId
	}
	return 0
}

type DeleteBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       int64                  `protobuf:"varint,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardRequest) Reset() {
	*x = DeleteBoardRequest{}
	mi := &file_board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardRequest) ProtoMessage() {}

func (x *DeleteBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardRequest.ProtoReflect.Descriptor instead.
func (*DeleteBoardRequest) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBoardRequest) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

type ChangeBoardNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       int64                  `protobuf:"varint,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeBoardNameRequest) Reset() {
	*x = ChangeBoardNameRequest{}
	mi := &file_board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeBoardNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBoardNameRequest) ProtoMessage() {}

func (x *ChangeBoardNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBoardNameRequest.ProtoReflect.Descriptor instead.
func (*ChangeBoardNameRequest) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeBoardNameRequest) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

func (x *ChangeBoardNameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type ChangeBoardNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeBoardNameResponse) Reset() {
	*x = ChangeBoardNameResponse{}
	mi := &file_board_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeBoardNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBoardNameResponse) ProtoMessage() {}

func (x *ChangeBoardNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBoardNameResponse.ProtoReflect.Descriptor instead.
func (*ChangeBoardNameResponse) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeBoardNameResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type ChangeBoardWallpapersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       int64                  `protobuf:"varint,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Wallpapers    []string               `protobuf:"bytes,2,rep,name=wallpapers,proto3" json:"wallpapers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeBoardWallpapersRequest) Reset() {
	*x = ChangeBoardWallpapersRequest{}
	mi := &file_board_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeBoardWallpapersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBoardWallpapersRequest) ProtoMessage() {}

func (x *ChangeBoardWallpapersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBoardWallpapersRequest.ProtoReflect.Descriptor instead.
func (*ChangeBoardWallpapersRequest) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeBoardWallpapersRequest) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

func (x *ChangeBoardWallpapersRequest) GetWallpapers() []string {
	if x != nil {
		return x.Wallpapers
	}
	return nil
}

type ChangeBoardWallpapersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeBoardWallpapersResponse) Reset() {
	*x = ChangeBoardWallpapersResponse{}
	mi := &file_board_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeBoardWallpapersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBoardWallpapersResponse) ProtoMessage() {}

func (x *ChangeBoardWallpapersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBoardWallpapersResponse.ProtoReflect.Descriptor instead.
func (*ChangeBoardWallpapersResponse) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeBoardWallpapersResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type GetBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       int64                  `protobuf:"varint,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardRequest) Reset() {
	*x = GetBoardRequest{}
	mi := &file_board_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardRequest) ProtoMessage() {}

func (x *GetBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardRequest.ProtoReflect.Descriptor instead.
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{13}
}

func (x *GetBoardRequest) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

var File_board_proto protoreflect.FileDescriptor

const file_board_proto_rawDesc = "" +
	"\n" +
	"\vboard.proto\x12\x05board\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x02\n" +
	"\x05Board\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10collaborator_ids\x18\x03 \x03(\x03R\x0fcollaboratorIds\x12\x1e\n" +
	"\n" +
	"wallpapers\x18\x04 \x03(\tR\n" +
	"wallpapers\x12!\n" +
	"\x05lists\x18\x05 \x03(\v2\v.board.ListR\x05lists\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc3\x01\n" +
	"\x04List\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\x05cards\x18\x03 \x03(\v2\v.board.CardR\x05cards\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9e\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fassignee_ids\x18\x04 \x03(\x03R\vassigneeIds\x125\n" +
	"\bdue_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"F\n" +
	"\x12CreateBoardRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\twallpapes\x18\x02 \x03(\tR\twallpapes\"9\n" +
	"\x13CreateBoardResponse\x12\"\n" +
	"\x05board\x18\x01 \x01(\v2\f.board.BoardR\x05board\"X\n" +
	"\x12CollaborateRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\x03R\aboardId\x12'\n" +
	"\x0fcollaborator_id\x18\x02 \x01(\x03R\x0ecollaboratorId\"9\n" +
	"\x13CollaborateResponse\x12\"\n" +
	"\x05board\x18\x01 \x01(\v2\f.board.BoardR\x05board\"_\n" +
	"\x19DeleteCollaboratorRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\x03R\aboardId\x12'\n" +
	"\x0fcollaborator_id\x18\x02 \x01(\x03R\x0ecollaboratorId\"/\n" +
	"\x12DeleteBoardRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\x03R\aboardId\"N\n" +
	"\x16ChangeBoardNameRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\x03R\aboardId\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"=\n" +
	"\x17ChangeBoardNameResponse\x12\"\n" +
	"\x05board\x18\x01 \x01(\v2\f.board.BoardR\x05board\"Y\n" +
	"\x1cChangeBoardWallpapersRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\x03R\aboardId\x12\x1e\n" +
	"\n" +
	"wallpapers\x18\x02 \x03(\tR\n" +
	"wallpapers\"C\n" +
	"\x1dChangeBoardWallpapersResponse\x12\"\n" +
	"\x05board\x18\x01 \x01(\v2\f.board.BoardR\x05board\",\n" +
	"\x0fGetBoardRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\x03R\aboardId2\x94\x04\n" +
	"\fBoardService\x12D\n" +
	"\vCreateBoard\x12\x19.board.CreateBoardRequest\x1a\x1a.board.CreateBoardResponse\x12D\n" +
	"\vCollaborate\x12\x19.board.CollaborateRequest\x1a\x1a.board.CollaborateResponse\x12N\n" +
	"\x12DeleteCollaborator\x12 .board.DeleteCollaboratorRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\vDeleteBoard\x12\x19.board.DeleteBoardRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x0fChangeBoardName\x12\x1d.board.ChangeBoardNameRequest\x1a\x1e.board.ChangeBoardNameResponse\x12b\n" +
	"\x15ChangeBoardWallpapers\x12#.board.ChangeBoardWallpapersRequest\x1a$.board.ChangeBoardWallpapersResponse\x120\n" +
	"\bGetBoard\x12\x16.board.GetBoardRequest\x1a\f.board.BoardB4Z2github.com/mmMikhailS/trello/internal/common/boardb\x06proto3"

var (
	file_board_proto_rawDescOnce sync.Once
	file_board_proto_rawDescData []byte
)

func file_board_proto_rawDescGZIP() []byte {
	file_board_proto_rawDescOnce.Do(func() {
		file_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_board_proto_rawDesc), len(file_board_proto_rawDesc)))
	})
	return file_board_proto_rawDescData
}

var file_board_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_board_proto_goTypes = []any{
	(*Board)(nil),                         // 0: board.Board
	(*List)(nil),                          // 1: board.List
	(*Card)(nil),                          // 2: board.Card
	(*CreateBoardRequest)(nil),            // 3: board.CreateBoardRequest
	(*CreateBoardResponse)(nil),           // 4: board.CreateBoardResponse
	(*CollaborateRequest)(nil),            // 5: board.CollaborateRequest
	(*CollaborateResponse)(nil),           // 6: board.CollaborateResponse
	(*DeleteCollaboratorRequest)(nil),     // 7: board.DeleteCollaboratorRequest
	(*DeleteBoardRequest)(nil),            // 8: board.DeleteBoardRequest
	(*ChangeBoardNameRequest)(nil),        // 9: board.ChangeBoardNameRequest
	(*ChangeBoardNameResponse)(nil),       // 10: board.ChangeBoardNameResponse
	(*ChangeBoardWallpapersRequest)(nil),  // 11: board.ChangeBoardWallpapersRequest
	(*ChangeBoardWallpapersResponse)(nil), // 12: board.ChangeBoardWallpapersResponse
	(*GetBoardRequest)(nil),               // 13: board.GetBoardRequest
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 15: google.protobuf.Empty
}
var file_board_proto_depIdxs = []int32{
	1,  // 0: board.Board.lists:type_name -> board.List
	14, // 1: board.Board.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: board.Board.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: board.List.cards:type_name -> board.Card
	14, // 4: board.List.created_at:type_name -> google.protobuf.Timestamp
	14, // 5: board.List.updated_at:type_name -> google.protobuf.Timestamp
	14, // 6: board.Card.due_date:type_name -> google.protobuf.Timestamp
	14, // 7: board.Card.created_at:type_name -> google.protobuf.Timestamp
	14, // 8: board.Card.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: board.CreateBoardResponse.board:type_name -> board.Board
	0,  // 10: board.CollaborateResponse.board:type_name -> board.Board
	0,  // 11: board.ChangeBoardNameResponse.board:type_name -> board.Board
	0,  // 12: board.ChangeBoardWallpapersResponse.board:type_name -> board.Board
	3,  // 13: board.BoardService.CreateBoard:input_type -> board.CreateBoardRequest
	5,  // 14: board.BoardService.Collaborate:input_type -> board.CollaborateRequest
	7,  // 15: board.BoardService.DeleteCollaborator:input_type -> board.DeleteCollaboratorRequest
	8,  // 16: board.BoardService.DeleteBoard:input_type -> board.DeleteBoardRequest
	9,  // 17: board.BoardService.ChangeBoardName:input_type -> board.ChangeBoardNameRequest
	11, // 18: board.BoardService.ChangeBoardWallpapers:input_type -> board.ChangeBoardWallpapersRequest
	13, // 19: board.BoardService.GetBoard:input_type -> board.GetBoardRequest
	4,  // 20: board.BoardService.CreateBoard:output_type -> board.CreateBoardResponse
	6,  // 21: board.BoardService.Collaborate:output_type -> board.CollaborateResponse
	15, // 22: board.BoardService.DeleteCollaborator:output_type -> google.protobuf.Empty
	15, // 23: board.BoardService.DeleteBoard:output_type -> google.protobuf.Empty
	10, // 24: board.BoardService.ChangeBoardName:output_type -> board.ChangeBoardNameResponse
	12, // 25: board.BoardService.ChangeBoardWallpapers:output_type -> board.ChangeBoardWallpapersResponse
	0,  // 26: board.BoardService.GetBoard:output_type -> board.Board
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_board_proto_init() }
func file_board_proto_init() {
	if File_board_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_board_proto_rawDesc), len(file_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_board_proto_goTypes,
		DependencyIndexes: file_board_proto_depIdxs,
		MessageInfos:      file_board_proto_msgTypes,
	}.Build()
	File_board_proto = out.File
	file_board_proto_goTypes = nil
	file_board_proto_depIdxs = nil
}
