// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: twofa.proto

package twofa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyLoginTOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           string                 `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyLoginTOTPRequest) Reset() {
	*x = VerifyLoginTOTPRequest{}
	mi := &file_twofa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyLoginTOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyLoginTOTPRequest) ProtoMessage() {}

func (x *VerifyLoginTOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyLoginTOTPRequest.ProtoReflect.Descriptor instead.
func (*VerifyLoginTOTPRequest) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyLoginTOTPRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type VerifyLoginTOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyLoginTOTPResponse) Reset() {
	*x = VerifyLoginTOTPResponse{}
	mi := &file_twofa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyLoginTOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyLoginTOTPResponse) ProtoMessage() {}

func (x *VerifyLoginTOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyLoginTOTPResponse.ProtoReflect.Descriptor instead.
func (*VerifyLoginTOTPResponse) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{1}
}

type InitVerifyLoginEmail2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitVerifyLoginEmail2FARequest) Reset() {
	*x = InitVerifyLoginEmail2FARequest{}
	mi := &file_twofa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitVerifyLoginEmail2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitVerifyLoginEmail2FARequest) ProtoMessage() {}

func (x *InitVerifyLoginEmail2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitVerifyLoginEmail2FARequest.ProtoReflect.Descriptor instead.
func (*InitVerifyLoginEmail2FARequest) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{2}
}

type InitVerifyLoginEmail2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpId         string                 `protobuf:"bytes,1,opt,name=otp_id,json=otpId,proto3" json:"otp_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitVerifyLoginEmail2FAResponse) Reset() {
	*x = InitVerifyLoginEmail2FAResponse{}
	mi := &file_twofa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitVerifyLoginEmail2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitVerifyLoginEmail2FAResponse) ProtoMessage() {}

func (x *InitVerifyLoginEmail2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitVerifyLoginEmail2FAResponse.ProtoReflect.Descriptor instead.
func (*InitVerifyLoginEmail2FAResponse) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{3}
}

func (x *InitVerifyLoginEmail2FAResponse) GetOtpId() string {
	if x != nil {
		return x.OtpId
	}
	return ""
}

func (x *InitVerifyLoginEmail2FAResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ConfirmVerifyLoginEmail2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpId         string                 `protobuf:"bytes,1,opt,name=otp_id,json=otpId,proto3" json:"otp_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmVerifyLoginEmail2FARequest) Reset() {
	*x = ConfirmVerifyLoginEmail2FARequest{}
	mi := &file_twofa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmVerifyLoginEmail2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmVerifyLoginEmail2FARequest) ProtoMessage() {}

func (x *ConfirmVerifyLoginEmail2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmVerifyLoginEmail2FARequest.ProtoReflect.Descriptor instead.
func (*ConfirmVerifyLoginEmail2FARequest) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmVerifyLoginEmail2FARequest) GetOtpId() string {
	if x != nil {
		return x.OtpId
	}
	return ""
}

func (x *ConfirmVerifyLoginEmail2FARequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ConfirmVerifyLoginEmail2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmVerifyLoginEmail2FAResponse) Reset() {
	*x = ConfirmVerifyLoginEmail2FAResponse{}
	mi := &file_twofa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmVerifyLoginEmail2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmVerifyLoginEmail2FAResponse) ProtoMessage() {}

func (x *ConfirmVerifyLoginEmail2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmVerifyLoginEmail2FAResponse.ProtoReflect.Descriptor instead.
func (*ConfirmVerifyLoginEmail2FAResponse) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{5}
}

type InitEnableEmail2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEnableEmail2FARequest) Reset() {
	*x = InitEnableEmail2FARequest{}
	mi := &file_twofa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEnableEmail2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEnableEmail2FARequest) ProtoMessage() {}

func (x *InitEnableEmail2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEnableEmail2FARequest.ProtoReflect.Descriptor instead.
func (*InitEnableEmail2FARequest) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{6}
}

func (x *InitEnableEmail2FARequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type InitEnableEmail2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpId         string                 `protobuf:"bytes,1,opt,name=otp_id,json=otpId,proto3" json:"otp_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEnableEmail2FAResponse) Reset() {
	*x = InitEnableEmail2FAResponse{}
	mi := &file_twofa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEnableEmail2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEnableEmail2FAResponse) ProtoMessage() {}

func (x *InitEnableEmail2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEnableEmail2FAResponse.ProtoReflect.Descriptor instead.
func (*InitEnableEmail2FAResponse) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{7}
}

func (x *InitEnableEmail2FAResponse) GetOtpId() string {
	if x != nil {
		return x.OtpId
	}
	return ""
}

func (x *InitEnableEmail2FAResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ConfirmEnableEmail2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpId         string                 `protobuf:"bytes,1,opt,name=otp_id,json=otpId,proto3" json:"otp_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmEnableEmail2FARequest) Reset() {
	*x = ConfirmEnableEmail2FARequest{}
	mi := &file_twofa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEnableEmail2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEnableEmail2FARequest) ProtoMessage() {}

func (x *ConfirmEnableEmail2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEnableEmail2FARequest.ProtoReflect.Descriptor instead.
func (*ConfirmEnableEmail2FARequest) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmEnableEmail2FARequest) GetOtpId() string {
	if x != nil {
		return x.OtpId
	}
	return ""
}

func (x *ConfirmEnableEmail2FARequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ConfirmEnableEmail2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmEnableEmail2FAResponse) Reset() {
	*x = ConfirmEnableEmail2FAResponse{}
	mi := &file_twofa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEnableEmail2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEnableEmail2FAResponse) ProtoMessage() {}

func (x *ConfirmEnableEmail2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEnableEmail2FAResponse.ProtoReflect.Descriptor instead.
func (*ConfirmEnableEmail2FAResponse) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{9}
}

type InitDisableEmail2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitDisableEmail2FARequest) Reset() {
	*x = InitDisableEmail2FARequest{}
	mi := &file_twofa_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitDisableEmail2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDisableEmail2FARequest) ProtoMessage() {}

func (x *InitDisableEmail2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitDisableEmail2FARequest.ProtoReflect.Descriptor instead.
func (*InitDisableEmail2FARequest) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{10}
}

func (x *InitDisableEmail2FARequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type InitDisableEmail2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpId         string                 `protobuf:"bytes,1,opt,name=otp_id,json=otpId,proto3" json:"otp_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitDisableEmail2FAResponse) Reset() {
	*x = InitDisableEmail2FAResponse{}
	mi := &file_twofa_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitDisableEmail2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDisableEmail2FAResponse) ProtoMessage() {}

func (x *InitDisableEmail2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitDisableEmail2FAResponse.ProtoReflect.Descriptor instead.
func (*InitDisableEmail2FAResponse) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{11}
}

func (x *InitDisableEmail2FAResponse) GetOtpId() string {
	if x != nil {
		return x.OtpId
	}
	return ""
}

func (x *InitDisableEmail2FAResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ConfirmDisableEmail2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpId         string                 `protobuf:"bytes,1,opt,name=otp_id,json=otpId,proto3" json:"otp_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDisableEmail2FARequest) Reset() {
	*x = ConfirmDisableEmail2FARequest{}
	mi := &file_twofa_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDisableEmail2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDisableEmail2FARequest) ProtoMessage() {}

func (x *ConfirmDisableEmail2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDisableEmail2FARequest.ProtoReflect.Descriptor instead.
func (*ConfirmDisableEmail2FARequest) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmDisableEmail2FARequest) GetOtpId() string {
	if x != nil {
		return x.OtpId
	}
	return ""
}

func (x *ConfirmDisableEmail2FARequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ConfirmDisableEmail2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDisableEmail2FAResponse) Reset() {
	*x = ConfirmDisableEmail2FAResponse{}
	mi := &file_twofa_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDisableEmail2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDisableEmail2FAResponse) ProtoMessage() {}

func (x *ConfirmDisableEmail2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDisableEmail2FAResponse.ProtoReflect.Descriptor instead.
func (*ConfirmDisableEmail2FAResponse) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{13}
}

type EnableTOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           string                 `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableTOTPRequest) Reset() {
	*x = EnableTOTPRequest{}
	mi := &file_twofa_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableTOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableTOTPRequest) ProtoMessage() {}

func (x *EnableTOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableTOTPRequest.ProtoReflect.Descriptor instead.
func (*EnableTOTPRequest) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{14}
}

func (x *EnableTOTPRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type EnableTOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableTOTPResponse) Reset() {
	*x = EnableTOTPResponse{}
	mi := &file_twofa_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableTOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableTOTPResponse) ProtoMessage() {}

func (x *EnableTOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableTOTPResponse.ProtoReflect.Descriptor instead.
func (*EnableTOTPResponse) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{15}
}

type DisableTOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           string                 `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableTOTPRequest) Reset() {
	*x = DisableTOTPRequest{}
	mi := &file_twofa_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableTOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableTOTPRequest) ProtoMessage() {}

func (x *DisableTOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableTOTPRequest.ProtoReflect.Descriptor instead.
func (*DisableTOTPRequest) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{16}
}

func (x *DisableTOTPRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type DisableTOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableTOTPResponse) Reset() {
	*x = DisableTOTPResponse{}
	mi := &file_twofa_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableTOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableTOTPResponse) ProtoMessage() {}

func (x *DisableTOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableTOTPResponse.ProtoReflect.Descriptor instead.
func (*DisableTOTPResponse) Descriptor() ([]byte, []int) {
	return file_twofa_proto_rawDescGZIP(), []int{17}
}

var File_twofa_proto protoreflect.FileDescriptor

const file_twofa_proto_rawDesc = "" +
	"\n" +
	"\vtwofa.proto\x12\x05twofa\"*\n" +
	"\x16VerifyLoginTOTPRequest\x12\x10\n" +
	"\x03otp\x18\x01 \x01(\tR\x03otp\"\x19\n" +
	"\x17VerifyLoginTOTPResponse\" \n" +
	"\x1eInitVerifyLoginEmail2FARequest\"W\n" +
	"\x1fInitVerifyLoginEmail2FAResponse\x12\x15\n" +
	"\x06otp_id\x18\x01 \x01(\tR\x05otpId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"N\n" +
	"!ConfirmVerifyLoginEmail2FARequest\x12\x15\n" +
	"\x06otp_id\x18\x01 \x01(\tR\x05otpId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"$\n" +
	"\"ConfirmVerifyLoginEmail2FAResponse\"7\n" +
	"\x19InitEnableEmail2FARequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"R\n" +
	"\x1aInitEnableEmail2FAResponse\x12\x15\n" +
	"\x06otp_id\x18\x01 \x01(\tR\x05otpId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"I\n" +
	"\x1cConfirmEnableEmail2FARequest\x12\x15\n" +
	"\x06otp_id\x18\x01 \x01(\tR\x05otpId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x1f\n" +
	"\x1dConfirmEnableEmail2FAResponse\"8\n" +
	"\x1aInitDisableEmail2FARequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"S\n" +
	"\x1bInitDisableEmail2FAResponse\x12\x15\n" +
	"\x06otp_id\x18\x01 \x01(\tR\x05otpId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"J\n" +
	"\x1dConfirmDisableEmail2FARequest\x12\x15\n" +
	"\x06otp_id\x18\x01 \x01(\tR\x05otpId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\" \n" +
	"\x1eConfirmDisableEmail2FAResponse\"%\n" +
	"\x11EnableTOTPRequest\x12\x10\n" +
	"\x03otp\x18\x01 \x01(\tR\x03otp\"\x14\n" +
	"\x12EnableTOTPResponse\"&\n" +
	"\x12DisableTOTPRequest\x12\x10\n" +
	"\x03otp\x18\x01 \x01(\tR\x03otp\"\x15\n" +
	"\x13DisableTOTPResponse2\xca\x06\n" +
	"\fTwofaService\x12P\n" +
	"\x0fVerifyLoginTOTP\x12\x1d.twofa.VerifyLoginTOTPRequest\x1a\x1e.twofa.VerifyLoginTOTPResponse\x12h\n" +
	"\x17InitVerifyLoginEmail2FA\x12%.twofa.InitVerifyLoginEmail2FARequest\x1a&.twofa.InitVerifyLoginEmail2FAResponse\x12q\n" +
	"\x1aConfirmVerifyLoginEmail2FA\x12(.twofa.ConfirmVerifyLoginEmail2FARequest\x1a).twofa.ConfirmVerifyLoginEmail2FAResponse\x12Y\n" +
	"\x12InitEnableEmail2FA\x12 .twofa.InitEnableEmail2FARequest\x1a!.twofa.InitEnableEmail2FAResponse\x12b\n" +
	"\x15ConfirmEnableEmail2FA\x12#.twofa.ConfirmEnableEmail2FARequest\x1a$.twofa.ConfirmEnableEmail2FAResponse\x12\\\n" +
	"\x13InitDisableEmail2FA\x12!.twofa.InitDisableEmail2FARequest\x1a\".twofa.InitDisableEmail2FAResponse\x12e\n" +
	"\x16ConfirmDisableEmail2FA\x12$.twofa.ConfirmDisableEmail2FARequest\x1a%.twofa.ConfirmDisableEmail2FAResponse\x12A\n" +
	"\n" +
	"EnableTOTP\x12\x18.twofa.EnableTOTPRequest\x1a\x19.twofa.EnableTOTPResponse\x12D\n" +
	"\vDisableTOTP\x12\x19.twofa.DisableTOTPRequest\x1a\x1a.twofa.DisableTOTPResponseB4Z2github.com/mmMikhailS/trello/internal/common/twofab\x06proto3"

var (
	file_twofa_proto_rawDescOnce sync.Once
	file_twofa_proto_rawDescData []byte
)

func file_twofa_proto_rawDescGZIP() []byte {
	file_twofa_proto_rawDescOnce.Do(func() {
		file_twofa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_twofa_proto_rawDesc), len(file_twofa_proto_rawDesc)))
	})
	return file_twofa_proto_rawDescData
}

var file_twofa_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_twofa_proto_goTypes = []any{
	(*VerifyLoginTOTPRequest)(nil),             // 0: twofa.VerifyLoginTOTPRequest
	(*VerifyLoginTOTPResponse)(nil),            // 1: twofa.VerifyLoginTOTPResponse
	(*InitVerifyLoginEmail2FARequest)(nil),     // 2: twofa.InitVerifyLoginEmail2FARequest
	(*InitVerifyLoginEmail2FAResponse)(nil),    // 3: twofa.InitVerifyLoginEmail2FAResponse
	(*ConfirmVerifyLoginEmail2FARequest)(nil),  // 4: twofa.ConfirmVerifyLoginEmail2FARequest
	(*ConfirmVerifyLoginEmail2FAResponse)(nil), // 5: twofa.ConfirmVerifyLoginEmail2FAResponse
	(*InitEnableEmail2FARequest)(nil),          // 6: twofa.InitEnableEmail2FARequest
	(*InitEnableEmail2FAResponse)(nil),         // 7: twofa.InitEnableEmail2FAResponse
	(*ConfirmEnableEmail2FARequest)(nil),       // 8: twofa.ConfirmEnableEmail2FARequest
	(*ConfirmEnableEmail2FAResponse)(nil),      // 9: twofa.ConfirmEnableEmail2FAResponse
	(*InitDisableEmail2FARequest)(nil),         // 10: twofa.InitDisableEmail2FARequest
	(*InitDisableEmail2FAResponse)(nil),        // 11: twofa.InitDisableEmail2FAResponse
	(*ConfirmDisableEmail2FARequest)(nil),      // 12: twofa.ConfirmDisableEmail2FARequest
	(*ConfirmDisableEmail2FAResponse)(nil),     // 13: twofa.ConfirmDisableEmail2FAResponse
	(*EnableTOTPRequest)(nil),                  // 14: twofa.EnableTOTPRequest
	(*EnableTOTPResponse)(nil),                 // 15: twofa.EnableTOTPResponse
	(*DisableTOTPRequest)(nil),                 // 16: twofa.DisableTOTPRequest
	(*DisableTOTPResponse)(nil),                // 17: twofa.DisableTOTPResponse
}
var file_twofa_proto_depIdxs = []int32{
	0,  // 0: twofa.TwofaService.VerifyLoginTOTP:input_type -> twofa.VerifyLoginTOTPRequest
	2,  // 1: twofa.TwofaService.InitVerifyLoginEmail2FA:input_type -> twofa.InitVerifyLoginEmail2FARequest
	4,  // 2: twofa.TwofaService.ConfirmVerifyLoginEmail2FA:input_type -> twofa.ConfirmVerifyLoginEmail2FARequest
	6,  // 3: twofa.TwofaService.InitEnableEmail2FA:input_type -> twofa.InitEnableEmail2FARequest
	8,  // 4: twofa.TwofaService.ConfirmEnableEmail2FA:input_type -> twofa.ConfirmEnableEmail2FARequest
	10, // 5: twofa.TwofaService.InitDisableEmail2FA:input_type -> twofa.InitDisableEmail2FARequest
	12, // 6: twofa.TwofaService.ConfirmDisableEmail2FA:input_type -> twofa.ConfirmDisableEmail2FARequest
	14, // 7: twofa.TwofaService.EnableTOTP:input_type -> twofa.EnableTOTPRequest
	16, // 8: twofa.TwofaService.DisableTOTP:input_type -> twofa.DisableTOTPRequest
	1,  // 9: twofa.TwofaService.VerifyLoginTOTP:output_type -> twofa.VerifyLoginTOTPResponse
	3,  // 10: twofa.TwofaService.InitVerifyLoginEmail2FA:output_type -> twofa.InitVerifyLoginEmail2FAResponse
	5,  // 11: twofa.TwofaService.ConfirmVerifyLoginEmail2FA:output_type -> twofa.ConfirmVerifyLoginEmail2FAResponse
	7,  // 12: twofa.TwofaService.InitEnableEmail2FA:output_type -> twofa.InitEnableEmail2FAResponse
	9,  // 13: twofa.TwofaService.ConfirmEnableEmail2FA:output_type -> twofa.ConfirmEnableEmail2FAResponse
	11, // 14: twofa.TwofaService.InitDisableEmail2FA:output_type -> twofa.InitDisableEmail2FAResponse
	13, // 15: twofa.TwofaService.ConfirmDisableEmail2FA:output_type -> twofa.ConfirmDisableEmail2FAResponse
	15, // 16: twofa.TwofaService.EnableTOTP:output_type -> twofa.EnableTOTPResponse
	17, // 17: twofa.TwofaService.DisableTOTP:output_type -> twofa.DisableTOTPResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_twofa_proto_init() }
func file_twofa_proto_init() {
	if File_twofa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_twofa_proto_rawDesc), len(file_twofa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_twofa_proto_goTypes,
		DependencyIndexes: file_twofa_proto_depIdxs,
		MessageInfos:      file_twofa_proto_msgTypes,
	}.Build()
	File_twofa_proto = out.File
	file_twofa_proto_goTypes = nil
	file_twofa_proto_depIdxs = nil
}
