// Package twofa provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package twofa

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ConfirmDisableEmail2FAWithBody request with any body
	ConfirmDisableEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ConfirmDisableEmail2FA(ctx context.Context, body ConfirmDisableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConfirmEnableEmail2FAWithBody request with any body
	ConfirmEnableEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ConfirmEnableEmail2FA(ctx context.Context, body ConfirmEnableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConfirmVerifyLoginEmail2FAWithBody request with any body
	ConfirmVerifyLoginEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ConfirmVerifyLoginEmail2FA(ctx context.Context, body ConfirmVerifyLoginEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DisableTOTPWithBody request with any body
	DisableTOTPWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DisableTOTP(ctx context.Context, body DisableTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EnableTOTPWithBody request with any body
	EnableTOTPWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	EnableTOTP(ctx context.Context, body EnableTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InitDisableEmail2FAWithBody request with any body
	InitDisableEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InitDisableEmail2FA(ctx context.Context, body InitDisableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InitEnableEmail2FAWithBody request with any body
	InitEnableEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InitEnableEmail2FA(ctx context.Context, body InitEnableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InitVerifyLoginEmail2FAWithBody request with any body
	InitVerifyLoginEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InitVerifyLoginEmail2FA(ctx context.Context, body InitVerifyLoginEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VerifyLoginTOTPWithBody request with any body
	VerifyLoginTOTPWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	VerifyLoginTOTP(ctx context.Context, body VerifyLoginTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ConfirmDisableEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfirmDisableEmail2FARequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConfirmDisableEmail2FA(ctx context.Context, body ConfirmDisableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfirmDisableEmail2FARequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConfirmEnableEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfirmEnableEmail2FARequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConfirmEnableEmail2FA(ctx context.Context, body ConfirmEnableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfirmEnableEmail2FARequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConfirmVerifyLoginEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfirmVerifyLoginEmail2FARequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConfirmVerifyLoginEmail2FA(ctx context.Context, body ConfirmVerifyLoginEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfirmVerifyLoginEmail2FARequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DisableTOTPWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDisableTOTPRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DisableTOTP(ctx context.Context, body DisableTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDisableTOTPRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EnableTOTPWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnableTOTPRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EnableTOTP(ctx context.Context, body EnableTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnableTOTPRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InitDisableEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitDisableEmail2FARequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InitDisableEmail2FA(ctx context.Context, body InitDisableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitDisableEmail2FARequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InitEnableEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitEnableEmail2FARequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InitEnableEmail2FA(ctx context.Context, body InitEnableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitEnableEmail2FARequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InitVerifyLoginEmail2FAWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitVerifyLoginEmail2FARequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InitVerifyLoginEmail2FA(ctx context.Context, body InitVerifyLoginEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitVerifyLoginEmail2FARequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VerifyLoginTOTPWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVerifyLoginTOTPRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VerifyLoginTOTP(ctx context.Context, body VerifyLoginTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVerifyLoginTOTPRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewConfirmDisableEmail2FARequest calls the generic ConfirmDisableEmail2FA builder with application/json body
func NewConfirmDisableEmail2FARequest(server string, body ConfirmDisableEmail2FAJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewConfirmDisableEmail2FARequestWithBody(server, "application/json", bodyReader)
}

// NewConfirmDisableEmail2FARequestWithBody generates requests for ConfirmDisableEmail2FA with any type of body
func NewConfirmDisableEmail2FARequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/twofa/confirmDisableEmail2FA")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewConfirmEnableEmail2FARequest calls the generic ConfirmEnableEmail2FA builder with application/json body
func NewConfirmEnableEmail2FARequest(server string, body ConfirmEnableEmail2FAJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewConfirmEnableEmail2FARequestWithBody(server, "application/json", bodyReader)
}

// NewConfirmEnableEmail2FARequestWithBody generates requests for ConfirmEnableEmail2FA with any type of body
func NewConfirmEnableEmail2FARequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/twofa/confirmEnableEmail2FA")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewConfirmVerifyLoginEmail2FARequest calls the generic ConfirmVerifyLoginEmail2FA builder with application/json body
func NewConfirmVerifyLoginEmail2FARequest(server string, body ConfirmVerifyLoginEmail2FAJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewConfirmVerifyLoginEmail2FARequestWithBody(server, "application/json", bodyReader)
}

// NewConfirmVerifyLoginEmail2FARequestWithBody generates requests for ConfirmVerifyLoginEmail2FA with any type of body
func NewConfirmVerifyLoginEmail2FARequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/twofa/confirmVerifyLoginEmail2FA")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDisableTOTPRequest calls the generic DisableTOTP builder with application/json body
func NewDisableTOTPRequest(server string, body DisableTOTPJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDisableTOTPRequestWithBody(server, "application/json", bodyReader)
}

// NewDisableTOTPRequestWithBody generates requests for DisableTOTP with any type of body
func NewDisableTOTPRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/twofa/disableTOTP")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewEnableTOTPRequest calls the generic EnableTOTP builder with application/json body
func NewEnableTOTPRequest(server string, body EnableTOTPJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEnableTOTPRequestWithBody(server, "application/json", bodyReader)
}

// NewEnableTOTPRequestWithBody generates requests for EnableTOTP with any type of body
func NewEnableTOTPRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/twofa/enableTOTP")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInitDisableEmail2FARequest calls the generic InitDisableEmail2FA builder with application/json body
func NewInitDisableEmail2FARequest(server string, body InitDisableEmail2FAJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInitDisableEmail2FARequestWithBody(server, "application/json", bodyReader)
}

// NewInitDisableEmail2FARequestWithBody generates requests for InitDisableEmail2FA with any type of body
func NewInitDisableEmail2FARequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/twofa/initDisableEmail2FA")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInitEnableEmail2FARequest calls the generic InitEnableEmail2FA builder with application/json body
func NewInitEnableEmail2FARequest(server string, body InitEnableEmail2FAJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInitEnableEmail2FARequestWithBody(server, "application/json", bodyReader)
}

// NewInitEnableEmail2FARequestWithBody generates requests for InitEnableEmail2FA with any type of body
func NewInitEnableEmail2FARequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/twofa/initEnableEmail2FA")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInitVerifyLoginEmail2FARequest calls the generic InitVerifyLoginEmail2FA builder with application/json body
func NewInitVerifyLoginEmail2FARequest(server string, body InitVerifyLoginEmail2FAJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInitVerifyLoginEmail2FARequestWithBody(server, "application/json", bodyReader)
}

// NewInitVerifyLoginEmail2FARequestWithBody generates requests for InitVerifyLoginEmail2FA with any type of body
func NewInitVerifyLoginEmail2FARequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/twofa/initVerifyLoginEmail2FA")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewVerifyLoginTOTPRequest calls the generic VerifyLoginTOTP builder with application/json body
func NewVerifyLoginTOTPRequest(server string, body VerifyLoginTOTPJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewVerifyLoginTOTPRequestWithBody(server, "application/json", bodyReader)
}

// NewVerifyLoginTOTPRequestWithBody generates requests for VerifyLoginTOTP with any type of body
func NewVerifyLoginTOTPRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/twofa/verifyLoginTOTP")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ConfirmDisableEmail2FAWithBodyWithResponse request with any body
	ConfirmDisableEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConfirmDisableEmail2FAResponse, error)

	ConfirmDisableEmail2FAWithResponse(ctx context.Context, body ConfirmDisableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*ConfirmDisableEmail2FAResponse, error)

	// ConfirmEnableEmail2FAWithBodyWithResponse request with any body
	ConfirmEnableEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConfirmEnableEmail2FAResponse, error)

	ConfirmEnableEmail2FAWithResponse(ctx context.Context, body ConfirmEnableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*ConfirmEnableEmail2FAResponse, error)

	// ConfirmVerifyLoginEmail2FAWithBodyWithResponse request with any body
	ConfirmVerifyLoginEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConfirmVerifyLoginEmail2FAResponse, error)

	ConfirmVerifyLoginEmail2FAWithResponse(ctx context.Context, body ConfirmVerifyLoginEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*ConfirmVerifyLoginEmail2FAResponse, error)

	// DisableTOTPWithBodyWithResponse request with any body
	DisableTOTPWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DisableTOTPResponse, error)

	DisableTOTPWithResponse(ctx context.Context, body DisableTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*DisableTOTPResponse, error)

	// EnableTOTPWithBodyWithResponse request with any body
	EnableTOTPWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnableTOTPResponse, error)

	EnableTOTPWithResponse(ctx context.Context, body EnableTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*EnableTOTPResponse, error)

	// InitDisableEmail2FAWithBodyWithResponse request with any body
	InitDisableEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitDisableEmail2FAResponse, error)

	InitDisableEmail2FAWithResponse(ctx context.Context, body InitDisableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*InitDisableEmail2FAResponse, error)

	// InitEnableEmail2FAWithBodyWithResponse request with any body
	InitEnableEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitEnableEmail2FAResponse, error)

	InitEnableEmail2FAWithResponse(ctx context.Context, body InitEnableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*InitEnableEmail2FAResponse, error)

	// InitVerifyLoginEmail2FAWithBodyWithResponse request with any body
	InitVerifyLoginEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitVerifyLoginEmail2FAResponse, error)

	InitVerifyLoginEmail2FAWithResponse(ctx context.Context, body InitVerifyLoginEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*InitVerifyLoginEmail2FAResponse, error)

	// VerifyLoginTOTPWithBodyWithResponse request with any body
	VerifyLoginTOTPWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VerifyLoginTOTPResponse, error)

	VerifyLoginTOTPWithResponse(ctx context.Context, body VerifyLoginTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*VerifyLoginTOTPResponse, error)
}

type ConfirmDisableEmail2FAResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConfirmDisableEmail2FAResponse
}

// Status returns HTTPResponse.Status
func (r ConfirmDisableEmail2FAResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConfirmDisableEmail2FAResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ConfirmEnableEmail2FAResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConfirmEnableEmail2FAResponse
}

// Status returns HTTPResponse.Status
func (r ConfirmEnableEmail2FAResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConfirmEnableEmail2FAResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ConfirmVerifyLoginEmail2FAResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConfirmVerifyLoginEmail2FAResponse
}

// Status returns HTTPResponse.Status
func (r ConfirmVerifyLoginEmail2FAResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConfirmVerifyLoginEmail2FAResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DisableTOTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DisableTOTPResponse
}

// Status returns HTTPResponse.Status
func (r DisableTOTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DisableTOTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type EnableTOTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnableTOTPResponse
}

// Status returns HTTPResponse.Status
func (r EnableTOTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EnableTOTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InitDisableEmail2FAResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InitDisableEmail2FAResponse
}

// Status returns HTTPResponse.Status
func (r InitDisableEmail2FAResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InitDisableEmail2FAResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InitEnableEmail2FAResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InitEnableEmail2FAResponse
}

// Status returns HTTPResponse.Status
func (r InitEnableEmail2FAResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InitEnableEmail2FAResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InitVerifyLoginEmail2FAResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InitVerifyLoginEmail2FAResponse
}

// Status returns HTTPResponse.Status
func (r InitVerifyLoginEmail2FAResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InitVerifyLoginEmail2FAResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VerifyLoginTOTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VerifyLoginTOTPResponse
}

// Status returns HTTPResponse.Status
func (r VerifyLoginTOTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VerifyLoginTOTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ConfirmDisableEmail2FAWithBodyWithResponse request with arbitrary body returning *ConfirmDisableEmail2FAResponse
func (c *ClientWithResponses) ConfirmDisableEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConfirmDisableEmail2FAResponse, error) {
	rsp, err := c.ConfirmDisableEmail2FAWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfirmDisableEmail2FAResponse(rsp)
}

func (c *ClientWithResponses) ConfirmDisableEmail2FAWithResponse(ctx context.Context, body ConfirmDisableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*ConfirmDisableEmail2FAResponse, error) {
	rsp, err := c.ConfirmDisableEmail2FA(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfirmDisableEmail2FAResponse(rsp)
}

// ConfirmEnableEmail2FAWithBodyWithResponse request with arbitrary body returning *ConfirmEnableEmail2FAResponse
func (c *ClientWithResponses) ConfirmEnableEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConfirmEnableEmail2FAResponse, error) {
	rsp, err := c.ConfirmEnableEmail2FAWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfirmEnableEmail2FAResponse(rsp)
}

func (c *ClientWithResponses) ConfirmEnableEmail2FAWithResponse(ctx context.Context, body ConfirmEnableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*ConfirmEnableEmail2FAResponse, error) {
	rsp, err := c.ConfirmEnableEmail2FA(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfirmEnableEmail2FAResponse(rsp)
}

// ConfirmVerifyLoginEmail2FAWithBodyWithResponse request with arbitrary body returning *ConfirmVerifyLoginEmail2FAResponse
func (c *ClientWithResponses) ConfirmVerifyLoginEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConfirmVerifyLoginEmail2FAResponse, error) {
	rsp, err := c.ConfirmVerifyLoginEmail2FAWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfirmVerifyLoginEmail2FAResponse(rsp)
}

func (c *ClientWithResponses) ConfirmVerifyLoginEmail2FAWithResponse(ctx context.Context, body ConfirmVerifyLoginEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*ConfirmVerifyLoginEmail2FAResponse, error) {
	rsp, err := c.ConfirmVerifyLoginEmail2FA(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfirmVerifyLoginEmail2FAResponse(rsp)
}

// DisableTOTPWithBodyWithResponse request with arbitrary body returning *DisableTOTPResponse
func (c *ClientWithResponses) DisableTOTPWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DisableTOTPResponse, error) {
	rsp, err := c.DisableTOTPWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDisableTOTPResponse(rsp)
}

func (c *ClientWithResponses) DisableTOTPWithResponse(ctx context.Context, body DisableTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*DisableTOTPResponse, error) {
	rsp, err := c.DisableTOTP(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDisableTOTPResponse(rsp)
}

// EnableTOTPWithBodyWithResponse request with arbitrary body returning *EnableTOTPResponse
func (c *ClientWithResponses) EnableTOTPWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnableTOTPResponse, error) {
	rsp, err := c.EnableTOTPWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnableTOTPResponse(rsp)
}

func (c *ClientWithResponses) EnableTOTPWithResponse(ctx context.Context, body EnableTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*EnableTOTPResponse, error) {
	rsp, err := c.EnableTOTP(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnableTOTPResponse(rsp)
}

// InitDisableEmail2FAWithBodyWithResponse request with arbitrary body returning *InitDisableEmail2FAResponse
func (c *ClientWithResponses) InitDisableEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitDisableEmail2FAResponse, error) {
	rsp, err := c.InitDisableEmail2FAWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitDisableEmail2FAResponse(rsp)
}

func (c *ClientWithResponses) InitDisableEmail2FAWithResponse(ctx context.Context, body InitDisableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*InitDisableEmail2FAResponse, error) {
	rsp, err := c.InitDisableEmail2FA(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitDisableEmail2FAResponse(rsp)
}

// InitEnableEmail2FAWithBodyWithResponse request with arbitrary body returning *InitEnableEmail2FAResponse
func (c *ClientWithResponses) InitEnableEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitEnableEmail2FAResponse, error) {
	rsp, err := c.InitEnableEmail2FAWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitEnableEmail2FAResponse(rsp)
}

func (c *ClientWithResponses) InitEnableEmail2FAWithResponse(ctx context.Context, body InitEnableEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*InitEnableEmail2FAResponse, error) {
	rsp, err := c.InitEnableEmail2FA(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitEnableEmail2FAResponse(rsp)
}

// InitVerifyLoginEmail2FAWithBodyWithResponse request with arbitrary body returning *InitVerifyLoginEmail2FAResponse
func (c *ClientWithResponses) InitVerifyLoginEmail2FAWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitVerifyLoginEmail2FAResponse, error) {
	rsp, err := c.InitVerifyLoginEmail2FAWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitVerifyLoginEmail2FAResponse(rsp)
}

func (c *ClientWithResponses) InitVerifyLoginEmail2FAWithResponse(ctx context.Context, body InitVerifyLoginEmail2FAJSONRequestBody, reqEditors ...RequestEditorFn) (*InitVerifyLoginEmail2FAResponse, error) {
	rsp, err := c.InitVerifyLoginEmail2FA(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitVerifyLoginEmail2FAResponse(rsp)
}

// VerifyLoginTOTPWithBodyWithResponse request with arbitrary body returning *VerifyLoginTOTPResponse
func (c *ClientWithResponses) VerifyLoginTOTPWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VerifyLoginTOTPResponse, error) {
	rsp, err := c.VerifyLoginTOTPWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVerifyLoginTOTPResponse(rsp)
}

func (c *ClientWithResponses) VerifyLoginTOTPWithResponse(ctx context.Context, body VerifyLoginTOTPJSONRequestBody, reqEditors ...RequestEditorFn) (*VerifyLoginTOTPResponse, error) {
	rsp, err := c.VerifyLoginTOTP(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVerifyLoginTOTPResponse(rsp)
}

// ParseConfirmDisableEmail2FAResponse parses an HTTP response from a ConfirmDisableEmail2FAWithResponse call
func ParseConfirmDisableEmail2FAResponse(rsp *http.Response) (*ConfirmDisableEmail2FAResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConfirmDisableEmail2FAResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConfirmDisableEmail2FAResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseConfirmEnableEmail2FAResponse parses an HTTP response from a ConfirmEnableEmail2FAWithResponse call
func ParseConfirmEnableEmail2FAResponse(rsp *http.Response) (*ConfirmEnableEmail2FAResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConfirmEnableEmail2FAResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConfirmEnableEmail2FAResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseConfirmVerifyLoginEmail2FAResponse parses an HTTP response from a ConfirmVerifyLoginEmail2FAWithResponse call
func ParseConfirmVerifyLoginEmail2FAResponse(rsp *http.Response) (*ConfirmVerifyLoginEmail2FAResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConfirmVerifyLoginEmail2FAResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConfirmVerifyLoginEmail2FAResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDisableTOTPResponse parses an HTTP response from a DisableTOTPWithResponse call
func ParseDisableTOTPResponse(rsp *http.Response) (*DisableTOTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DisableTOTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DisableTOTPResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseEnableTOTPResponse parses an HTTP response from a EnableTOTPWithResponse call
func ParseEnableTOTPResponse(rsp *http.Response) (*EnableTOTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EnableTOTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnableTOTPResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseInitDisableEmail2FAResponse parses an HTTP response from a InitDisableEmail2FAWithResponse call
func ParseInitDisableEmail2FAResponse(rsp *http.Response) (*InitDisableEmail2FAResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InitDisableEmail2FAResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InitDisableEmail2FAResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseInitEnableEmail2FAResponse parses an HTTP response from a InitEnableEmail2FAWithResponse call
func ParseInitEnableEmail2FAResponse(rsp *http.Response) (*InitEnableEmail2FAResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InitEnableEmail2FAResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InitEnableEmail2FAResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseInitVerifyLoginEmail2FAResponse parses an HTTP response from a InitVerifyLoginEmail2FAWithResponse call
func ParseInitVerifyLoginEmail2FAResponse(rsp *http.Response) (*InitVerifyLoginEmail2FAResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InitVerifyLoginEmail2FAResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InitVerifyLoginEmail2FAResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseVerifyLoginTOTPResponse parses an HTTP response from a VerifyLoginTOTPWithResponse call
func ParseVerifyLoginTOTPResponse(rsp *http.Response) (*VerifyLoginTOTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VerifyLoginTOTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VerifyLoginTOTPResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
