// Package twofa provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package twofa

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ConfirmDisableEmail2FARequest defines model for ConfirmDisableEmail2FARequest.
type ConfirmDisableEmail2FARequest struct {
	Code  string `json:"code"`
	OtpId string `json:"otp_id"`
}

// ConfirmDisableEmail2FAResponse Empty response
type ConfirmDisableEmail2FAResponse = map[string]interface{}

// ConfirmEnableEmail2FARequest defines model for ConfirmEnableEmail2FARequest.
type ConfirmEnableEmail2FARequest struct {
	Code  string `json:"code"`
	OtpId string `json:"otp_id"`
}

// ConfirmEnableEmail2FAResponse Empty response
type ConfirmEnableEmail2FAResponse = map[string]interface{}

// ConfirmVerifyLoginEmail2FARequest defines model for ConfirmVerifyLoginEmail2FARequest.
type ConfirmVerifyLoginEmail2FARequest struct {
	Code  string `json:"code"`
	OtpId string `json:"otp_id"`
}

// ConfirmVerifyLoginEmail2FAResponse Empty response
type ConfirmVerifyLoginEmail2FAResponse = map[string]interface{}

// DisableTOTPRequest defines model for DisableTOTPRequest.
type DisableTOTPRequest struct {
	Otp string `json:"otp"`
}

// DisableTOTPResponse Empty response
type DisableTOTPResponse = map[string]interface{}

// EnableTOTPRequest defines model for EnableTOTPRequest.
type EnableTOTPRequest struct {
	Otp string `json:"otp"`
}

// EnableTOTPResponse Empty response
type EnableTOTPResponse = map[string]interface{}

// InitDisableEmail2FARequest defines model for InitDisableEmail2FARequest.
type InitDisableEmail2FARequest struct {
	Password string `json:"password"`
}

// InitDisableEmail2FAResponse defines model for InitDisableEmail2FAResponse.
type InitDisableEmail2FAResponse struct {
	ExpiresAt int64  `json:"expires_at"`
	OtpId     string `json:"otp_id"`
}

// InitEnableEmail2FARequest defines model for InitEnableEmail2FARequest.
type InitEnableEmail2FARequest struct {
	Password string `json:"password"`
}

// InitEnableEmail2FAResponse defines model for InitEnableEmail2FAResponse.
type InitEnableEmail2FAResponse struct {
	ExpiresAt int64  `json:"expires_at"`
	OtpId     string `json:"otp_id"`
}

// InitVerifyLoginEmail2FARequest Empty request
type InitVerifyLoginEmail2FARequest = map[string]interface{}

// InitVerifyLoginEmail2FAResponse defines model for InitVerifyLoginEmail2FAResponse.
type InitVerifyLoginEmail2FAResponse struct {
	ExpiresAt int64  `json:"expires_at"`
	OtpId     string `json:"otp_id"`
}

// VerifyLoginTOTPRequest defines model for VerifyLoginTOTPRequest.
type VerifyLoginTOTPRequest struct {
	Otp string `json:"otp"`
}

// VerifyLoginTOTPResponse Empty response
type VerifyLoginTOTPResponse = map[string]interface{}

// ConfirmDisableEmail2FAJSONRequestBody defines body for ConfirmDisableEmail2FA for application/json ContentType.
type ConfirmDisableEmail2FAJSONRequestBody = ConfirmDisableEmail2FARequest

// ConfirmEnableEmail2FAJSONRequestBody defines body for ConfirmEnableEmail2FA for application/json ContentType.
type ConfirmEnableEmail2FAJSONRequestBody = ConfirmEnableEmail2FARequest

// ConfirmVerifyLoginEmail2FAJSONRequestBody defines body for ConfirmVerifyLoginEmail2FA for application/json ContentType.
type ConfirmVerifyLoginEmail2FAJSONRequestBody = ConfirmVerifyLoginEmail2FARequest

// DisableTOTPJSONRequestBody defines body for DisableTOTP for application/json ContentType.
type DisableTOTPJSONRequestBody = DisableTOTPRequest

// EnableTOTPJSONRequestBody defines body for EnableTOTP for application/json ContentType.
type EnableTOTPJSONRequestBody = EnableTOTPRequest

// InitDisableEmail2FAJSONRequestBody defines body for InitDisableEmail2FA for application/json ContentType.
type InitDisableEmail2FAJSONRequestBody = InitDisableEmail2FARequest

// InitEnableEmail2FAJSONRequestBody defines body for InitEnableEmail2FA for application/json ContentType.
type InitEnableEmail2FAJSONRequestBody = InitEnableEmail2FARequest

// InitVerifyLoginEmail2FAJSONRequestBody defines body for InitVerifyLoginEmail2FA for application/json ContentType.
type InitVerifyLoginEmail2FAJSONRequestBody = InitVerifyLoginEmail2FARequest

// VerifyLoginTOTPJSONRequestBody defines body for VerifyLoginTOTP for application/json ContentType.
type VerifyLoginTOTPJSONRequestBody = VerifyLoginTOTPRequest
