// Package board provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package board

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Board defines model for Board.
type Board struct {
	CollaboratorIds *[]int64   `json:"collaborator_ids,omitempty"`
	CreatedAt       *time.Time `json:"created_at,omitempty"`
	Id              *int64     `json:"id,omitempty"`
	Lists           *[]List    `json:"lists,omitempty"`
	Name            *string    `json:"name,omitempty"`
	UpdatedAt       *time.Time `json:"updated_at,omitempty"`
	Wallpapers      *[]string  `json:"wallpapers,omitempty"`
}

// Card defines model for Card.
type Card struct {
	AssigneeIds *[]int64   `json:"assignee_ids,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"due_date,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	Title       *string    `json:"title,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
}

// ChangeBoardNameRequest defines model for ChangeBoardNameRequest.
type ChangeBoardNameRequest struct {
	NewName string `json:"new_name"`
}

// ChangeBoardNameResponse defines model for ChangeBoardNameResponse.
type ChangeBoardNameResponse struct {
	Board *Board `json:"board,omitempty"`
}

// ChangeBoardWallpapersRequest defines model for ChangeBoardWallpapersRequest.
type ChangeBoardWallpapersRequest struct {
	Wallpapers []string `json:"wallpapers"`
}

// ChangeBoardWallpapersResponse defines model for ChangeBoardWallpapersResponse.
type ChangeBoardWallpapersResponse struct {
	Board *Board `json:"board,omitempty"`
}

// CollaborateRequest defines model for CollaborateRequest.
type CollaborateRequest struct {
	CollaboratorId int64 `json:"collaborator_id"`
}

// CreateBoardRequest defines model for CreateBoardRequest.
type CreateBoardRequest struct {
	Name       string    `json:"name"`
	Wallpapers *[]string `json:"wallpapers,omitempty"`
}

// CreateBoardResponse defines model for CreateBoardResponse.
type CreateBoardResponse struct {
	Board *Board `json:"board,omitempty"`
}

// List defines model for List.
type List struct {
	Cards     *[]Card    `json:"cards,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// CreateBoardJSONRequestBody defines body for CreateBoard for application/json ContentType.
type CreateBoardJSONRequestBody = CreateBoardRequest

// AddCollaboratorJSONRequestBody defines body for AddCollaborator for application/json ContentType.
type AddCollaboratorJSONRequestBody = CollaborateRequest

// ChangeBoardNameJSONRequestBody defines body for ChangeBoardName for application/json ContentType.
type ChangeBoardNameJSONRequestBody = ChangeBoardNameRequest

// ChangeBoardWallpapersJSONRequestBody defines body for ChangeBoardWallpapers for application/json ContentType.
type ChangeBoardWallpapersJSONRequestBody = ChangeBoardWallpapersRequest
