// Package board provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package board

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateBoardWithBody request with any body
	CreateBoardWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateBoard(ctx context.Context, body CreateBoardJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBoard request
	DeleteBoard(ctx context.Context, boardId int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBoard request
	GetBoard(ctx context.Context, boardId int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddCollaboratorWithBody request with any body
	AddCollaboratorWithBody(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddCollaborator(ctx context.Context, boardId int64, body AddCollaboratorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteCollaborator request
	DeleteCollaborator(ctx context.Context, boardId int64, collaboratorId int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ChangeBoardNameWithBody request with any body
	ChangeBoardNameWithBody(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChangeBoardName(ctx context.Context, boardId int64, body ChangeBoardNameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ChangeBoardWallpapersWithBody request with any body
	ChangeBoardWallpapersWithBody(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChangeBoardWallpapers(ctx context.Context, boardId int64, body ChangeBoardWallpapersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateBoardWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBoardRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateBoard(ctx context.Context, body CreateBoardJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBoardRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteBoard(ctx context.Context, boardId int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBoardRequest(c.Server, boardId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBoard(ctx context.Context, boardId int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBoardRequest(c.Server, boardId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddCollaboratorWithBody(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddCollaboratorRequestWithBody(c.Server, boardId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddCollaborator(ctx context.Context, boardId int64, body AddCollaboratorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddCollaboratorRequest(c.Server, boardId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteCollaborator(ctx context.Context, boardId int64, collaboratorId int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteCollaboratorRequest(c.Server, boardId, collaboratorId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChangeBoardNameWithBody(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangeBoardNameRequestWithBody(c.Server, boardId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChangeBoardName(ctx context.Context, boardId int64, body ChangeBoardNameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangeBoardNameRequest(c.Server, boardId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChangeBoardWallpapersWithBody(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangeBoardWallpapersRequestWithBody(c.Server, boardId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChangeBoardWallpapers(ctx context.Context, boardId int64, body ChangeBoardWallpapersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangeBoardWallpapersRequest(c.Server, boardId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateBoardRequest calls the generic CreateBoard builder with application/json body
func NewCreateBoardRequest(server string, body CreateBoardJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateBoardRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateBoardRequestWithBody generates requests for CreateBoard with any type of body
func NewCreateBoardRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/boards")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteBoardRequest generates requests for DeleteBoard
func NewDeleteBoardRequest(server string, boardId int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "board_id", boardId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/boards/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBoardRequest generates requests for GetBoard
func NewGetBoardRequest(server string, boardId int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "board_id", boardId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/boards/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddCollaboratorRequest calls the generic AddCollaborator builder with application/json body
func NewAddCollaboratorRequest(server string, boardId int64, body AddCollaboratorJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddCollaboratorRequestWithBody(server, boardId, "application/json", bodyReader)
}

// NewAddCollaboratorRequestWithBody generates requests for AddCollaborator with any type of body
func NewAddCollaboratorRequestWithBody(server string, boardId int64, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "board_id", boardId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/boards/%s/collaborators", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteCollaboratorRequest generates requests for DeleteCollaborator
func NewDeleteCollaboratorRequest(server string, boardId int64, collaboratorId int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "board_id", boardId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "collaborator_id", collaboratorId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/boards/%s/collaborators/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewChangeBoardNameRequest calls the generic ChangeBoardName builder with application/json body
func NewChangeBoardNameRequest(server string, boardId int64, body ChangeBoardNameJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChangeBoardNameRequestWithBody(server, boardId, "application/json", bodyReader)
}

// NewChangeBoardNameRequestWithBody generates requests for ChangeBoardName with any type of body
func NewChangeBoardNameRequestWithBody(server string, boardId int64, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "board_id", boardId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/boards/%s/name", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewChangeBoardWallpapersRequest calls the generic ChangeBoardWallpapers builder with application/json body
func NewChangeBoardWallpapersRequest(server string, boardId int64, body ChangeBoardWallpapersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChangeBoardWallpapersRequestWithBody(server, boardId, "application/json", bodyReader)
}

// NewChangeBoardWallpapersRequestWithBody generates requests for ChangeBoardWallpapers with any type of body
func NewChangeBoardWallpapersRequestWithBody(server string, boardId int64, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "board_id", boardId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/boards/%s/wallpapers", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateBoardWithBodyWithResponse request with any body
	CreateBoardWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBoardResponse, error)

	CreateBoardWithResponse(ctx context.Context, body CreateBoardJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBoardResponse, error)

	// DeleteBoardWithResponse request
	DeleteBoardWithResponse(ctx context.Context, boardId int64, reqEditors ...RequestEditorFn) (*DeleteBoardResponse, error)

	// GetBoardWithResponse request
	GetBoardWithResponse(ctx context.Context, boardId int64, reqEditors ...RequestEditorFn) (*GetBoardResponse, error)

	// AddCollaboratorWithBodyWithResponse request with any body
	AddCollaboratorWithBodyWithResponse(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddCollaboratorResponse, error)

	AddCollaboratorWithResponse(ctx context.Context, boardId int64, body AddCollaboratorJSONRequestBody, reqEditors ...RequestEditorFn) (*AddCollaboratorResponse, error)

	// DeleteCollaboratorWithResponse request
	DeleteCollaboratorWithResponse(ctx context.Context, boardId int64, collaboratorId int64, reqEditors ...RequestEditorFn) (*DeleteCollaboratorResponse, error)

	// ChangeBoardNameWithBodyWithResponse request with any body
	ChangeBoardNameWithBodyWithResponse(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChangeBoardNameResponse, error)

	ChangeBoardNameWithResponse(ctx context.Context, boardId int64, body ChangeBoardNameJSONRequestBody, reqEditors ...RequestEditorFn) (*ChangeBoardNameResponse, error)

	// ChangeBoardWallpapersWithBodyWithResponse request with any body
	ChangeBoardWallpapersWithBodyWithResponse(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChangeBoardWallpapersResponse, error)

	ChangeBoardWallpapersWithResponse(ctx context.Context, boardId int64, body ChangeBoardWallpapersJSONRequestBody, reqEditors ...RequestEditorFn) (*ChangeBoardWallpapersResponse, error)
}

type CreateBoardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateBoardResponse
}

// Status returns HTTPResponse.Status
func (r CreateBoardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateBoardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteBoardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteBoardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteBoardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetBoardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Board
}

// Status returns HTTPResponse.Status
func (r GetBoardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBoardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddCollaboratorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Board
}

// Status returns HTTPResponse.Status
func (r AddCollaboratorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddCollaboratorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteCollaboratorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteCollaboratorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteCollaboratorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ChangeBoardNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChangeBoardNameResponse
}

// Status returns HTTPResponse.Status
func (r ChangeBoardNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChangeBoardNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ChangeBoardWallpapersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChangeBoardWallpapersResponse
}

// Status returns HTTPResponse.Status
func (r ChangeBoardWallpapersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChangeBoardWallpapersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateBoardWithBodyWithResponse request with arbitrary body returning *CreateBoardResponse
func (c *ClientWithResponses) CreateBoardWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBoardResponse, error) {
	rsp, err := c.CreateBoardWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBoardResponse(rsp)
}

func (c *ClientWithResponses) CreateBoardWithResponse(ctx context.Context, body CreateBoardJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBoardResponse, error) {
	rsp, err := c.CreateBoard(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBoardResponse(rsp)
}

// DeleteBoardWithResponse request returning *DeleteBoardResponse
func (c *ClientWithResponses) DeleteBoardWithResponse(ctx context.Context, boardId int64, reqEditors ...RequestEditorFn) (*DeleteBoardResponse, error) {
	rsp, err := c.DeleteBoard(ctx, boardId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBoardResponse(rsp)
}

// GetBoardWithResponse request returning *GetBoardResponse
func (c *ClientWithResponses) GetBoardWithResponse(ctx context.Context, boardId int64, reqEditors ...RequestEditorFn) (*GetBoardResponse, error) {
	rsp, err := c.GetBoard(ctx, boardId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBoardResponse(rsp)
}

// AddCollaboratorWithBodyWithResponse request with arbitrary body returning *AddCollaboratorResponse
func (c *ClientWithResponses) AddCollaboratorWithBodyWithResponse(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddCollaboratorResponse, error) {
	rsp, err := c.AddCollaboratorWithBody(ctx, boardId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddCollaboratorResponse(rsp)
}

func (c *ClientWithResponses) AddCollaboratorWithResponse(ctx context.Context, boardId int64, body AddCollaboratorJSONRequestBody, reqEditors ...RequestEditorFn) (*AddCollaboratorResponse, error) {
	rsp, err := c.AddCollaborator(ctx, boardId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddCollaboratorResponse(rsp)
}

// DeleteCollaboratorWithResponse request returning *DeleteCollaboratorResponse
func (c *ClientWithResponses) DeleteCollaboratorWithResponse(ctx context.Context, boardId int64, collaboratorId int64, reqEditors ...RequestEditorFn) (*DeleteCollaboratorResponse, error) {
	rsp, err := c.DeleteCollaborator(ctx, boardId, collaboratorId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteCollaboratorResponse(rsp)
}

// ChangeBoardNameWithBodyWithResponse request with arbitrary body returning *ChangeBoardNameResponse
func (c *ClientWithResponses) ChangeBoardNameWithBodyWithResponse(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChangeBoardNameResponse, error) {
	rsp, err := c.ChangeBoardNameWithBody(ctx, boardId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangeBoardNameResponse(rsp)
}

func (c *ClientWithResponses) ChangeBoardNameWithResponse(ctx context.Context, boardId int64, body ChangeBoardNameJSONRequestBody, reqEditors ...RequestEditorFn) (*ChangeBoardNameResponse, error) {
	rsp, err := c.ChangeBoardName(ctx, boardId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangeBoardNameResponse(rsp)
}

// ChangeBoardWallpapersWithBodyWithResponse request with arbitrary body returning *ChangeBoardWallpapersResponse
func (c *ClientWithResponses) ChangeBoardWallpapersWithBodyWithResponse(ctx context.Context, boardId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChangeBoardWallpapersResponse, error) {
	rsp, err := c.ChangeBoardWallpapersWithBody(ctx, boardId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangeBoardWallpapersResponse(rsp)
}

func (c *ClientWithResponses) ChangeBoardWallpapersWithResponse(ctx context.Context, boardId int64, body ChangeBoardWallpapersJSONRequestBody, reqEditors ...RequestEditorFn) (*ChangeBoardWallpapersResponse, error) {
	rsp, err := c.ChangeBoardWallpapers(ctx, boardId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangeBoardWallpapersResponse(rsp)
}

// ParseCreateBoardResponse parses an HTTP response from a CreateBoardWithResponse call
func ParseCreateBoardResponse(rsp *http.Response) (*CreateBoardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateBoardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateBoardResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteBoardResponse parses an HTTP response from a DeleteBoardWithResponse call
func ParseDeleteBoardResponse(rsp *http.Response) (*DeleteBoardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteBoardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetBoardResponse parses an HTTP response from a GetBoardWithResponse call
func ParseGetBoardResponse(rsp *http.Response) (*GetBoardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBoardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Board
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAddCollaboratorResponse parses an HTTP response from a AddCollaboratorWithResponse call
func ParseAddCollaboratorResponse(rsp *http.Response) (*AddCollaboratorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddCollaboratorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Board
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteCollaboratorResponse parses an HTTP response from a DeleteCollaboratorWithResponse call
func ParseDeleteCollaboratorResponse(rsp *http.Response) (*DeleteCollaboratorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteCollaboratorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseChangeBoardNameResponse parses an HTTP response from a ChangeBoardNameWithResponse call
func ParseChangeBoardNameResponse(rsp *http.Response) (*ChangeBoardNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChangeBoardNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChangeBoardNameResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseChangeBoardWallpapersResponse parses an HTTP response from a ChangeBoardWallpapersWithResponse call
func ParseChangeBoardWallpapersResponse(rsp *http.Response) (*ChangeBoardWallpapersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChangeBoardWallpapersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChangeBoardWallpapersResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
